services:
  - type: web
    name: login-analytics-system
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://brijendray200_db_user:brij@123@cluster0.5zbe8kn.mongodb.net/login-tracker?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: mysecretjwtkey123456789abcdef
      - key: REFRESH_TOKEN_SECRET
        value: myrefreshsecretkey123456789abcdef
      - key: EMAIL_USER
        value: brijendray200@gmail.com
      - key: EMAIL_PASS
        value: rvlmxczyhicbzrzz
      - key: FRONTEND_URL
        value: https://cosmic-seahorse-7d6f00.netlify.app
      - key: PORT
        value: 3000
